### ISSUE TITLE
Should not Equals_Same3_AreEqual pass with Assert.True(e);

### ISSUE THREAD

**Issue by mdmoura** [yesmarket/yesmarket.Linq.Expressions#1]
Hello,

Should not the following test be Assert.True(e) and pass?

```
    [Fact]
    public void Equals_Same3_AreEqual()
    {
        Expression<Func<Order, bool>> x = order => order.Customer == new Customer { Name = "john" };
        Expression<Func<Order, bool>> y = order => order.Customer == new Customer { Name = "john" };
        var e = _sut.Equals(x, y);
        Assert.False(e);
    }
```

Thank You,
Miguel

**Comment by yesmarket** [comment]
Thanks Miguel,

I think the assertion is actually correct, as the expressions, x & y, are comparing order.Customer to different objects i.e. expression "x" is comparing object.Customer to one instance of a customer, while expression "y" is comparing object.Customer to a different instance of customer.

I've re-written the unit test as follows, which is more in-line with my intent:
        [Fact]
        public void Equals_Same3_AreEqual()
        {
            var customer = new Customer { Name = "john" };
            Expression<Func<Order, bool>> x = order => order.Customer == customer;
            Expression<Func<Order, bool>> y = order => order.Customer == customer;
            var e = _sut.Equals(x, y);
            e.ShouldBeTrue();
        }

Let me know if this makes sense... also thank you for helping.

Ryan.
